// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: connect6.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServerClient is the client API for GameServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServerClient interface {
	Play(ctx context.Context, opts ...grpc.CallOption) (GameServer_PlayClient, error)
}

type gameServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServerClient(cc grpc.ClientConnInterface) GameServerClient {
	return &gameServerClient{cc}
}

func (c *gameServerClient) Play(ctx context.Context, opts ...grpc.CallOption) (GameServer_PlayClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameServer_ServiceDesc.Streams[0], "/connect6.GameServer/Play", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServerPlayClient{stream}
	return x, nil
}

type GameServer_PlayClient interface {
	Send(*PlayerAction) error
	Recv() (*GameState, error)
	grpc.ClientStream
}

type gameServerPlayClient struct {
	grpc.ClientStream
}

func (x *gameServerPlayClient) Send(m *PlayerAction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServerPlayClient) Recv() (*GameState, error) {
	m := new(GameState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServerServer is the server API for GameServer service.
// All implementations must embed UnimplementedGameServerServer
// for forward compatibility
type GameServerServer interface {
	Play(GameServer_PlayServer) error
	mustEmbedUnimplementedGameServerServer()
}

// UnimplementedGameServerServer must be embedded to have forward compatible implementations.
type UnimplementedGameServerServer struct {
}

func (UnimplementedGameServerServer) Play(GameServer_PlayServer) error {
	return status.Errorf(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedGameServerServer) mustEmbedUnimplementedGameServerServer() {}

// UnsafeGameServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServerServer will
// result in compilation errors.
type UnsafeGameServerServer interface {
	mustEmbedUnimplementedGameServerServer()
}

func RegisterGameServerServer(s grpc.ServiceRegistrar, srv GameServerServer) {
	s.RegisterService(&GameServer_ServiceDesc, srv)
}

func _GameServer_Play_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServerServer).Play(&gameServerPlayServer{stream})
}

type GameServer_PlayServer interface {
	Send(*GameState) error
	Recv() (*PlayerAction, error)
	grpc.ServerStream
}

type gameServerPlayServer struct {
	grpc.ServerStream
}

func (x *gameServerPlayServer) Send(m *GameState) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServerPlayServer) Recv() (*PlayerAction, error) {
	m := new(PlayerAction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServer_ServiceDesc is the grpc.ServiceDesc for GameServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connect6.GameServer",
	HandlerType: (*GameServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Play",
			Handler:       _GameServer_Play_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connect6.proto",
}
