// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: connect6.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerColor int32

const (
	PlayerColor_UNKNOWN PlayerColor = 0
	PlayerColor_BLACK   PlayerColor = 1
	PlayerColor_WHITE   PlayerColor = 2
)

// Enum value maps for PlayerColor.
var (
	PlayerColor_name = map[int32]string{
		0: "UNKNOWN",
		1: "BLACK",
		2: "WHITE",
	}
	PlayerColor_value = map[string]int32{
		"UNKNOWN": 0,
		"BLACK":   1,
		"WHITE":   2,
	}
)

func (x PlayerColor) Enum() *PlayerColor {
	p := new(PlayerColor)
	*p = x
	return p
}

func (x PlayerColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerColor) Descriptor() protoreflect.EnumDescriptor {
	return file_connect6_proto_enumTypes[0].Descriptor()
}

func (PlayerColor) Type() protoreflect.EnumType {
	return &file_connect6_proto_enumTypes[0]
}

func (x PlayerColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerColor.Descriptor instead.
func (PlayerColor) EnumDescriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{0}
}

type GameResult int32

const (
	GameResult_ONGOING       GameResult = 0
	GameResult_BLACK_WIN     GameResult = 1
	GameResult_WHITE_WIN     GameResult = 2
	GameResult_DRAW          GameResult = 3
	GameResult_BLACK_TIMEOUT GameResult = 4
	GameResult_WHITE_TIMEOUT GameResult = 5
	GameResult_BLACK_INVALID GameResult = 6
	GameResult_WHITE_INVALID GameResult = 7
)

// Enum value maps for GameResult.
var (
	GameResult_name = map[int32]string{
		0: "ONGOING",
		1: "BLACK_WIN",
		2: "WHITE_WIN",
		3: "DRAW",
		4: "BLACK_TIMEOUT",
		5: "WHITE_TIMEOUT",
		6: "BLACK_INVALID",
		7: "WHITE_INVALID",
	}
	GameResult_value = map[string]int32{
		"ONGOING":       0,
		"BLACK_WIN":     1,
		"WHITE_WIN":     2,
		"DRAW":          3,
		"BLACK_TIMEOUT": 4,
		"WHITE_TIMEOUT": 5,
		"BLACK_INVALID": 6,
		"WHITE_INVALID": 7,
	}
)

func (x GameResult) Enum() *GameResult {
	p := new(GameResult)
	*p = x
	return p
}

func (x GameResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResult) Descriptor() protoreflect.EnumDescriptor {
	return file_connect6_proto_enumTypes[1].Descriptor()
}

func (GameResult) Type() protoreflect.EnumType {
	return &file_connect6_proto_enumTypes[1]
}

func (x GameResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResult.Descriptor instead.
func (GameResult) EnumDescriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{1}
}

type GameState_Status int32

const (
	GameState_WAITING  GameState_Status = 0
	GameState_PLAYING  GameState_Status = 1
	GameState_FINISHED GameState_Status = 2
)

// Enum value maps for GameState_Status.
var (
	GameState_Status_name = map[int32]string{
		0: "WAITING",
		1: "PLAYING",
		2: "FINISHED",
	}
	GameState_Status_value = map[string]int32{
		"WAITING":  0,
		"PLAYING":  1,
		"FINISHED": 2,
	}
)

func (x GameState_Status) Enum() *GameState_Status {
	p := new(GameState_Status)
	*p = x
	return p
}

func (x GameState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_connect6_proto_enumTypes[2].Descriptor()
}

func (GameState_Status) Type() protoreflect.EnumType {
	return &file_connect6_proto_enumTypes[2]
}

func (x GameState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState_Status.Descriptor instead.
func (GameState_Status) EnumDescriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{4, 0}
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect6_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*PlayerAction_RegisterTeam
	//	*PlayerAction_Move
	//	*PlayerAction_Resign
	Action isPlayerAction_Action `protobuf_oneof:"action"`
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect6_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{1}
}

func (m *PlayerAction) GetAction() isPlayerAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *PlayerAction) GetRegisterTeam() string {
	if x, ok := x.GetAction().(*PlayerAction_RegisterTeam); ok {
		return x.RegisterTeam
	}
	return ""
}

func (x *PlayerAction) GetMove() *Move {
	if x, ok := x.GetAction().(*PlayerAction_Move); ok {
		return x.Move
	}
	return nil
}

func (x *PlayerAction) GetResign() bool {
	if x, ok := x.GetAction().(*PlayerAction_Resign); ok {
		return x.Resign
	}
	return false
}

type isPlayerAction_Action interface {
	isPlayerAction_Action()
}

type PlayerAction_RegisterTeam struct {
	RegisterTeam string `protobuf:"bytes,1,opt,name=register_team,json=registerTeam,proto3,oneof"`
}

type PlayerAction_Move struct {
	Move *Move `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type PlayerAction_Resign struct {
	Resign bool `protobuf:"varint,3,opt,name=resign,proto3,oneof"`
}

func (*PlayerAction_RegisterTeam) isPlayerAction_Action() {}

func (*PlayerAction_Move) isPlayerAction_Action() {}

func (*PlayerAction_Resign) isPlayerAction_Action() {}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stones []*Point `protobuf:"bytes,1,rep,name=stones,proto3" json:"stones,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect6_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{2}
}

func (x *Move) GetStones() []*Point {
	if x != nil {
		return x.Stones
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cells []PlayerColor `protobuf:"varint,1,rep,packed,name=cells,proto3,enum=connect6.PlayerColor" json:"cells,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect6_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetCells() []PlayerColor {
	if x != nil {
		return x.Cells
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         GameState_Status `protobuf:"varint,1,opt,name=status,proto3,enum=connect6.GameState_Status" json:"status,omitempty"`
	IsMyTurn       bool             `protobuf:"varint,2,opt,name=is_my_turn,json=isMyTurn,proto3" json:"is_my_turn,omitempty"`
	MyColor        PlayerColor      `protobuf:"varint,3,opt,name=my_color,json=myColor,proto3,enum=connect6.PlayerColor" json:"my_color,omitempty"`
	OpponentStones []*Point         `protobuf:"bytes,4,rep,name=opponent_stones,json=opponentStones,proto3" json:"opponent_stones,omitempty"`
	StonesRequired int32            `protobuf:"varint,5,opt,name=stones_required,json=stonesRequired,proto3" json:"stones_required,omitempty"`
	Message        string           `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Winner         PlayerColor      `protobuf:"varint,7,opt,name=winner,proto3,enum=connect6.PlayerColor" json:"winner,omitempty"`
	Result         GameResult       `protobuf:"varint,8,opt,name=result,proto3,enum=connect6.GameResult" json:"result,omitempty"`
	Board          []*Row           `protobuf:"bytes,9,rep,name=board,proto3" json:"board,omitempty"`
}

func (x *GameState) Reset() {
	*x = GameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect6_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{4}
}

func (x *GameState) GetStatus() GameState_Status {
	if x != nil {
		return x.Status
	}
	return GameState_WAITING
}

func (x *GameState) GetIsMyTurn() bool {
	if x != nil {
		return x.IsMyTurn
	}
	return false
}

func (x *GameState) GetMyColor() PlayerColor {
	if x != nil {
		return x.MyColor
	}
	return PlayerColor_UNKNOWN
}

func (x *GameState) GetOpponentStones() []*Point {
	if x != nil {
		return x.OpponentStones
	}
	return nil
}

func (x *GameState) GetStonesRequired() int32 {
	if x != nil {
		return x.StonesRequired
	}
	return 0
}

func (x *GameState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameState) GetWinner() PlayerColor {
	if x != nil {
		return x.Winner
	}
	return PlayerColor_UNKNOWN
}

func (x *GameState) GetResult() GameResult {
	if x != nil {
		return x.Result
	}
	return GameResult_ONGOING
}

func (x *GameState) GetBoard() []*Row {
	if x != nil {
		return x.Board
	}
	return nil
}

var File_connect6_proto protoreflect.FileDescriptor

var file_connect6_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22,
	0x7f, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x25, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x61, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x24, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x2f, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x6e,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x36, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x6e, 0x65,
	0x73, 0x22, 0x32, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x65, 0x6c, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x36, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05,
	0x63, 0x65, 0x6c, 0x6c, 0x73, 0x22, 0xc0, 0x03, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x6d, 0x79,
	0x5f, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4d,
	0x79, 0x54, 0x75, 0x72, 0x6e, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x36, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x07,
	0x6d, 0x79, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x38, 0x0a, 0x0f, 0x6f, 0x70, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x0e, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x6e, 0x65,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x74, 0x6f, 0x6e,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x06, 0x77, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e, 0x52, 0x6f, 0x77, 0x52,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x30, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49,
	0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x30, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x57, 0x48, 0x49, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x8d, 0x01, 0x0a, 0x0a, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x47,
	0x4f, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x5f,
	0x57, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x48, 0x49, 0x54, 0x45, 0x5f, 0x57,
	0x49, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x52, 0x41, 0x57, 0x10, 0x03, 0x12, 0x11,
	0x0a, 0x0d, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10,
	0x04, 0x12, 0x11, 0x0a, 0x0d, 0x57, 0x48, 0x49, 0x54, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f,
	0x55, 0x54, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x5f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x57, 0x48, 0x49, 0x54, 0x45,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x07, 0x32, 0x45, 0x0a, 0x0a, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79,
	0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x36, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x36, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_connect6_proto_rawDescOnce sync.Once
	file_connect6_proto_rawDescData = file_connect6_proto_rawDesc
)

func file_connect6_proto_rawDescGZIP() []byte {
	file_connect6_proto_rawDescOnce.Do(func() {
		file_connect6_proto_rawDescData = protoimpl.X.CompressGZIP(file_connect6_proto_rawDescData)
	})
	return file_connect6_proto_rawDescData
}

var file_connect6_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_connect6_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_connect6_proto_goTypes = []interface{}{
	(PlayerColor)(0),      // 0: connect6.PlayerColor
	(GameResult)(0),       // 1: connect6.GameResult
	(GameState_Status)(0), // 2: connect6.GameState.Status
	(*Point)(nil),         // 3: connect6.Point
	(*PlayerAction)(nil),  // 4: connect6.PlayerAction
	(*Move)(nil),          // 5: connect6.Move
	(*Row)(nil),           // 6: connect6.Row
	(*GameState)(nil),     // 7: connect6.GameState
}
var file_connect6_proto_depIdxs = []int32{
	5,  // 0: connect6.PlayerAction.move:type_name -> connect6.Move
	3,  // 1: connect6.Move.stones:type_name -> connect6.Point
	0,  // 2: connect6.Row.cells:type_name -> connect6.PlayerColor
	2,  // 3: connect6.GameState.status:type_name -> connect6.GameState.Status
	0,  // 4: connect6.GameState.my_color:type_name -> connect6.PlayerColor
	3,  // 5: connect6.GameState.opponent_stones:type_name -> connect6.Point
	0,  // 6: connect6.GameState.winner:type_name -> connect6.PlayerColor
	1,  // 7: connect6.GameState.result:type_name -> connect6.GameResult
	6,  // 8: connect6.GameState.board:type_name -> connect6.Row
	4,  // 9: connect6.GameServer.Play:input_type -> connect6.PlayerAction
	7,  // 10: connect6.GameServer.Play:output_type -> connect6.GameState
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_connect6_proto_init() }
func file_connect6_proto_init() {
	if File_connect6_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connect6_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect6_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect6_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect6_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect6_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_connect6_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PlayerAction_RegisterTeam)(nil),
		(*PlayerAction_Move)(nil),
		(*PlayerAction_Resign)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connect6_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connect6_proto_goTypes,
		DependencyIndexes: file_connect6_proto_depIdxs,
		EnumInfos:         file_connect6_proto_enumTypes,
		MessageInfos:      file_connect6_proto_msgTypes,
	}.Build()
	File_connect6_proto = out.File
	file_connect6_proto_rawDesc = nil
	file_connect6_proto_goTypes = nil
	file_connect6_proto_depIdxs = nil
}
